services:
  - type: web
    name: rgb-studio-server
    runtime: node
    rootDir: server
    buildCommand: npm install --include=dev && npx prisma generate --schema=prisma/schema.prisma && npm run build
    startCommand: node dist/main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
